import { FileText, ShieldAlert, CheckCircle2, HelpCircle, PhoneCall } from 'lucide-react';
import { useLocale } from '../hooks/useLocale';
import { Card } from '../components/ui/Card';
import { Link } from 'react-router';

export default function TermsPage() {
  const { locale } = useLocale();
  const isHi = locale === 'hi';

  return (
    <div className="min-h-screen py-10 px-4 sm:px-6 lg:px-8 max-w-5xl mx-auto flex flex-col gap-10">
      {/* Header Banner */}
      <div className="border-b border-[var(--line)] pb-6 flex flex-col gap-3">
        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-[var(--surface-2)] text-xs font-mono text-[var(--accent)] uppercase tracking-wider self-start">
          <FileText className="w-3.5 h-3.5" />
          {isHi ? 'सेवा की शर्तें एवं नियम' : 'Terms of Service & Hospital Charter'}
        </div>
        <h1 className="font-display text-3xl sm:text-4xl font-bold text-[var(--text)]">
          {isHi ? 'लैंथेरा स्वास्थ्य सेवा शर्तें और अस्पताल चार्टर' : 'Terms of Service & Clinical Care Charter'}
        </h1>
        <p className="text-sm text-[var(--text-muted)] max-w-3xl leading-relaxed">
          {isHi
            ? 'लैंथेरा हेल्थ की डिजिटल सेवाओं, अपॉइंटमेंट बुकिंग, पारदर्शी बिलिंग (Clear Ledger) और 24×7 आपातकालीन देखभाल के उपयोग के नियम।'
            : 'Governing terms for accessing Lanthera Health digital tools, specialist appointment bookings, Clear Ledger cost estimations, and hospital triage services.'}
        </p>
      </div>

      {/* Highlights Grid */}
      <div className="grid sm:grid-cols-3 gap-6">
        <Card shape="lantern" className="p-6 flex flex-col gap-3 bg-[var(--surface-2)] hover-lift">
          <ShieldAlert className="w-8 h-8 text-[var(--emergency)]" />
          <h3 className="font-display font-bold text-lg text-[var(--text)]">
            {isHi ? '24×7 आपातकालीन प्रोटोकॉल' : '24×7 ER Priority Standard'}
          </h3>
          <p className="text-xs text-[var(--text-muted)] leading-relaxed">
            Emergency patients presenting with Level-1 red flags are immediately triaged without pre-payment delays.
          </p>
        </Card>

        <Card shape="lantern" className="p-6 flex flex-col gap-3 bg-[var(--surface-2)] hover-lift">
          <CheckCircle2 className="w-8 h-8 text-[var(--sage)]" />
          <h3 className="font-display font-bold text-lg text-[var(--text)]">
            {isHi ? 'क्लियर लेजर गारंटी' : 'Clear Ledger Assurance'}
          </h3>
          <p className="text-xs text-[var(--text-muted)] leading-relaxed">
            All surgical and OPD estimate ranges are provided with transparent itemized breakdowns prior to admission.
          </p>
        </Card>

        <Card shape="lantern" className="p-6 flex flex-col gap-3 bg-[var(--surface-2)] hover-lift">
          <HelpCircle className="w-8 h-8 text-[var(--accent)]" />
          <h3 className="font-display font-bold text-lg text-[var(--text)]">
            {isHi ? 'रोगी अधिकार चार्टर' : 'Patient Rights & Respect'}
          </h3>
          <p className="text-xs text-[var(--text-muted)] leading-relaxed">
            Every patient has the right to second opinions, clear diagnostic explanations, and respectful care.
          </p>
        </Card>
      </div>

      {/* Terms Sections */}
      <div className="flex flex-col gap-6 text-sm text-[var(--text-muted)]">
        <section className="bg-[var(--surface)] border border-[var(--line)] p-6 sm:p-8 rounded-[var(--radius-lg)] flex flex-col gap-4 shadow-md">
          <h2 className="font-display text-xl font-bold text-[var(--text)] flex items-center gap-2">
            <CheckCircle2 className="w-5 h-5 text-[var(--accent)]" />
            <span>1. Specialist Appointment Booking & Scheduling</span>
          </h2>
          <p className="text-xs sm:text-sm leading-relaxed">
            Consultation time slots booked via the website or mobile portal reserve clinical time with senior specialists. Rescheduling or cancellation is permitted up to 2 hours before the appointment window.
          </p>
        </section>

        <section className="bg-[var(--surface)] border border-[var(--line)] p-6 sm:p-8 rounded-[var(--radius-lg)] flex flex-col gap-4 shadow-md">
          <h2 className="font-display text-xl font-bold text-[var(--text)] flex items-center gap-2">
            <CheckCircle2 className="w-5 h-5 text-[var(--accent)]" />
            <span>2. Pre-Procedure Financial Transparency</span>
          </h2>
          <p className="text-xs sm:text-sm leading-relaxed">
            Cost estimates generated by the Clear Ledger tool reflect current hospital room rates, procedure fees, and diagnostic ranges. Final billing adheres strictly to published tariff schedules with no hidden admin fees.
          </p>
        </section>

        <section className="bg-[var(--surface)] border border-[var(--line)] p-6 sm:p-8 rounded-[var(--radius-lg)] flex flex-col gap-4 shadow-md">
          <h2 className="font-display text-xl font-bold text-[var(--text)] flex items-center gap-2">
            <CheckCircle2 className="w-5 h-5 text-[var(--accent)]" />
            <span>3. Plain-Language Diagnostic Explanations</span>
          </h2>
          <p className="text-xs sm:text-sm leading-relaxed">
            Plain-language summaries provided in the Lantern Portal are intended for patient education and medical literacy. They complement, but do not replace, direct clinical consultation with your attending doctor.
          </p>
        </section>
      </div>

      {/* Emergency Contact Bar */}
      <div className="bg-[var(--surface-2)] border border-[var(--emergency)]/40 p-6 rounded-[var(--radius-lg)] flex flex-col sm:flex-row items-center justify-between gap-4 text-center sm:text-left">
        <div>
          <h4 className="font-display font-bold text-base text-[var(--text)]">
            Have questions regarding hospital policies or emergency admission?
          </h4>
          <p className="text-xs text-[var(--text-muted)] mt-0.5">
            Our 24×7 Patient Relations Desk is available at all hours.
          </p>
        </div>
        <Link to="/emergency">
          <div className="inline-flex items-center gap-2 bg-[var(--emergency)] text-white font-mono font-bold text-xs px-5 py-2.5 rounded-full hover:opacity-95 transition-opacity">
            <PhoneCall className="w-4 h-4" />
            24×7 Emergency Desk
          </div>
        </Link>
      </div>
    </div>
  );
}
